#!/bin/sh

set -e
fn=$(basename $0)

echo "$fn:Enabling apache2 service, by symlinking /etc/services.d/10-apache2 to /etc/service"
# Use the runit logger fifo
#rm -rf /etc/services.d/10-apache2/log
ln -s /etc/services.d/10-apache2 /etc/service/
ln -s /etc/apache2/sites-available/default.vhost /etc/apache2/sites-enabled/

