#!/usr/bin/env bash

hubid=hwdm
tag=$(grep -o "V=.*" $(pwd)/Dockerfile | tr -d V= | tr -d . | tr -d '[:space:]')
sudo docker build --force-rm --tag "${hubid}/apsnginx:${tag}" .
sudo docker tag "${hubid}/apsnginx:${tag}" "${hubid}/apsnginx:latest"
