#!/usr/bin/env bash

hubid=hwdm
tag=$(grep -o "WV=.*" $(pwd)/Dockerfile | tr -d WV= | tr -d . | tr -d '[:space:]')
sudo docker build --force-rm --tag "${hubid}/aprwpbase:${tag}" .
sudo docker tag "${hubid}/aprwpbase:${tag}" "${hubid}/aprwpbase:latest"
