#!/usr/bin/env bash

hubid=hwdm
tag=$(grep -o "S6OVERLAY_VERSION=.*" $(pwd)/Dockerfile | tr -d S6OVERLAY_VERSION=v | tr -d . | tr -d '[:space:]')
sudo docker build --force-rm --tag "${hubid}/aps6mark:${tag}" .
sudo docker tag "${hubid}/aps6mark:${tag}" "${hubid}/aps6mark:latest"
