#!/usr/bin/env bash

hubid=hwdm
tag=$(grep -o "VVV=.*" $(pwd)/Dockerfile | tr -d VVV= | tr -d . | tr -d '[:space:]')
sudo docker build --force-rm --tag "${hubid}/apswpmux:${tag}" .
sudo docker tag "${hubid}/apswpmux:${tag}" "${hubid}/apswpmux:latest"
