#!/bin/sh

## Ref: http://manpages.ubuntu.com/manpages/zesty/man8/php-fpm7.0.8.html

echo "... ... Starting Service php-fpm[php-fpm7] ... ..."

# Close STDOUT file descriptor
exec 1<&-
# Close STDERR FD
exec 2<&-

# Open STDOUT as a file for read and write.
exec 1<>/var/log/runsvdir/phpfpm7.log

# Redirect STDERR to STDOUT
exec 2>&1

echo "Startup log of the command line: sux www-data php-fpm7 --nodaemonize --pid /run/php/php-fpm.pid --php-ini /etc/php7/php.ini --fpm-config /etc/php7/php-fpm.conf"
echo "............................................................................................."

[ -r /etc/envvars ] && . /etc/envvars

exec php-fpm7 --nodaemonize --pid /run/php7/php-fpm.pid --php-ini /etc/php7/php.ini --fpm-config /etc/php7/php-fpm.conf

echo '... ... Service php-fpm[php-fpm7] Started Successfully ... ...'
