#!/bin/sh

set -e
fn=$(basename $0)

echo "$fn:Enabling php-fpm service, by symlinking /etc/services.d/php-fpm to /etc/service"

mkdir -p /var/run/php /var/run/php/sessions /var/log/php
chown www-data:www-data /var/run/php /var/run/php/sessions /var/log/php

ln -sf /etc/services.d/php-fpm /etc/service
