#!/usr/bin/env bash

hubid=hwdm
tag=$(grep -o "CONSUL_VERSION=.*" $(pwd)/Dockerfile | tr -d CONSUL_VERSION= | tr -d . | tr -d '[:space:]')
sudo docker build --force-rm --tag "${hubid}/aps6consul:${tag}" .
sudo docker tag "${hubid}/aps6consul:${tag}" "${hubid}/aps6consul:latest"
