#!/usr/bin/env bash

hubid=hwdm
tag=$(grep -o "V=.*" $(pwd)/Dockerfile | tr -d V= | tr -d . | tr -d -)
sudo docker build --force-rm --tag "${hubid}/aprapache:${tag}" .
sudo docker tag "${hubid}/aprapache:${tag}" "${hubid}/aprapache:latest"
