#!/bin/sh

set -e

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/httpd.pid
rm -f /run/apache2/httpd.pid
rm -f ${APACHE_PID_FILE}

echo "... ... Starting Service apache2 ... ..."

# Close STDOUT file descriptor
exec 1<&-
# Close STDERR FD
exec 2<&-

# Open STDOUT as a file for read and write.
exec 1<>/var/log/runsvdir/apache2.log

# Redirect STDERR to STDOUT
exec 2>&1

echo "Startup log of the command line: exec httpd -D FOREGROUND -f /etc/apache2/httpd.conf -k start"
echo "............................................................................................."

[ -r /etc/envvars ] && . /etc/envvars

exec httpd -D FOREGROUND -f /etc/apache2/httpd.conf -k start

echo '... ... Service apache2 Started Successfully ... ...'

