#!/bin/sh

set -e
fn=$(basename $0)

echo "$fn:Enabling nginx service, by symlinking /etc/services.d/nginx to /etc/service"

mkdir -p /var/run/nginx /var/log/nginx
chown www-data:www-data /var/run/nginx /var/log/nginx 

ln -sf /etc/services.d/nginx /etc/service

