#!/bin/sh

set -e
fn=$(basename $0)
mkdir -p /var/log/runsvdir
mkdir -p /run/nginx /run/cache/nginx /var/log/nginx
chown www-data:www-data /run/nginx /run/cache/nginx /var/log/nginx
echo "$fn:Enabling nginx service, by symlinking /etc/services.d/10-nginx to /etc/service"
ln -sf /etc/services.d/10-nginx /etc/service

echo "Server Mode is ${_SERVER_MODE}"
case ${_SERVER_MODE} in
    fcgi | FCGI | phpfpm | PHPFPM)
        if [ -r "/etc/ssl/${_SERVER_NAME}/${_SSL_CERT}.crt" ]; then
            rm -f /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost" && cp /etc/nginx/sites-available/sslphpfpm.vhost /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost"
            sed -i s"/_SERVER_NAME_/${_SERVER_NAME}/" /etc/nginx/conf.d/ssl.conf
            sed -i s"/_SSL_CERT_/${_SSL_CERT}/" /etc/nginx/conf.d/ssl.conf
            sed -i s"/^#ssl_certificate/ssl_certificate/" /etc/nginx/conf.d/ssl.conf
            sed -i s"/^#ssl_certificate_key/ssl_certificate_key/" /etc/nginx/conf.d/ssl.conf
            _LISTEN_TO1=$(escape $(unquote ${_LISTEN_TO1}))
            sed -i s"/_LISTEN_TO_/${_LISTEN_TO1}/g" /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost"
            sed -i s"/_SERVER_NAME_/${_SERVER_NAME}/g" /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost"
            sed -i s"/_DOC_ROOT_/$(escape ${_DOC_ROOT})/g" /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost"
        else
            rm -f /etc/nginx/sites-enabled/"${_SERVER_NAME}.vhost" ] && cp /etc/nginx/sites-available/phpfpm.vhost /etc/nginx/sites-enabled/"${_SERVER_NAME}.vhost"
            sed -i s"/_SERVER_NAME_/${_SERVER_NAME}/g" /etc/nginx/sites-enabled/"${_SERVER_NAME}.vhost"
            sed -i s"/_DOC_ROOT_/$(escape ${_DOC_ROOT})/g" /etc/nginx/sites-enabled/"${_SERVER_NAME}.vhost"
            _LISTEN_TO1=$(escape $(unquote ${_LISTEN_TO1}))
            sed -i s"/_LISTEN_TO_/${_LISTEN_TO1}/g" /etc/nginx/sites-enabled/"${_SERVER_NAME}.vhost"
        fi
    ;;
    fcgilb2 | FCGILB2 | lb2 | LB2)
    ;;
    fcgilb3 | FCGILB3 | lb3 | LB3)
    ;;
    direct | simple | DIRECT | SIMPLE)
        if [ -r "/etc/ssl/${_SERVER_NAME}/${_SSL_CERT}.crt" ]; then
            rm -f /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost" && cp /etc/nginx/sites-available/ssldirect.vhost /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost"
            sed -i s"/_SERVER_NAME_/${_SERVER_NAME}/" /etc/nginx/conf.d/ssl.conf
            sed -i s"/_SSL_CERT_/${_SSL_CERT}/" /etc/nginx/conf.d/ssl.conf
            sed -i s"/^#ssl_certificate/ssl_certificate/" /etc/nginx/conf.d/ssl.conf
            sed -i s"/^#ssl_certificate_key/ssl_certificate_key/" /etc/nginx/conf.d/ssl.conf
            sed -i s"/_SERVER_NAME_/${_SERVER_NAME}/g" /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost"
            sed -i s"/_DOC_ROOT_/$(escape ${_DOC_ROOT})/g" /etc/nginx/sites-enabled/"ssl${_SERVER_NAME}.vhost"
        else
            rm -f /etc/nginx/sites-enabled/${_SERVER_NAME} ] && cp /etc/nginx/sites-available/direct.vhost /etc/nginx/sites-enabled/"${_SERVER_NAME}.vhost"
            sed -i s"/_SERVER_NAME_/${_SERVER_NAME}/g" /etc/nginx/sites-enabled/"${_SERVER_NAME}.vhost"
            sed -i s"/_DOC_ROOT_/$(escape ${_DOC_ROOT})/g" /etc/nginx/sites-enabled/"${_SERVER_NAME}.vhost"
        fi
    ;;
    -- | *)
    ;;
esac

unset fn
